### PR TITLE
Support Minecraft 26.2 (Paper/Spigot) & fix Spigot startup

### LINKED ISSUE #1005: Published Paper jar crashes on pure Spigot since #998
## Summary
Since the MiniMessage migration (#998, commit `dd2c453a`, merged 2026-07-13), the `HuskHomes-Paper-*.jar` artifact — which is also the file published for the `spigot` loader on Modrinth/Hangar — no longer contains the Adventure core classes it references, and nothing provides them on a pure Spigot server. The plugin should fail to enable there with a `NoClassDefFoundError` for `net/kyori/adventure/...` classes.
I found this via artifact inspection while preparing Paper 26.2 support, so this report is based on static evidence rather than a live crash log — it should be quick to confirm by starting a current alpha build on any pure Spigot server.

## Affected builds
All alpha-channel builds since 2026-07-13. Verified against `HuskHomes-Paper-4.11-ab42970.jar` downloaded from Modrinth (built from current master).

## Evidence
1. #998 added `shadowJar` dependency excludes in `paper/build.gradle` for `adventure-api`, `adventure-text-minimessage`, all serializers, `adventure-key`, etc., with the rationale "Paper provides Adventure API + MiniMessage natively". That is correct for Paper — but the same jar is what CI publishes for the `spigot` loader (`files-primary: target/HuskHomes-Paper-*.jar`, loaders `spigot | paper | folia`).
2. Inspecting the published jar: the only `net.kyori` classes remaining are the 111 entries under `net/kyori/adventure/platform/**` (adventure-platform-bukkit). No `adventure-api`, no MiniMessage, no serializers.
3. The `plugin.yml` inside the jar (the descriptor Spigot uses, `main: BukkitHuskHomes`) declares libraries: for Jedis and the JDBC drivers only — Adventure is not supplied via Spigot's library loader either.
4. Classes in the jar reference unrelocated `net.kyori.adventure` types throughout (`MiniMessage, Component, Title, Sound, …`), and on the Spigot path `BukkitHuskHomes#createAudiences()` calls `BukkitAudiences.create(...)` — the bundled adventure-platform-bukkit also cannot function without the excluded Adventure core.
5. Pure Spigot ships no Adventure at all → first touch of any of these classes throws `NoClassDefFoundError`.
Paper is unaffected: `paper-plugin.yml` takes precedence there, `PaperHuskHomes#createAudiences()` is a no-op, and the server provides Adventure natively.

## Suggested fix

Option A (minimal, keeps the Paper-native design): add the excluded Adventure artifacts (`adventure-api`, `adventure-text-minimessage`, the serializers used, pinned to 4.26.1) to `plugin.yml`'s libraries: so Spigot's library loader downloads them at runtime, exactly like the JDBC drivers. Paper ignores `plugin.yml` when `paper-plugin.yml` is present, so the Paper path stays on the server's native Adventure — which also matters for 26.2, where Paper ships Adventure 5.

Option B: publish the separate `HuskHomes-Bukkit` shadow jar (which bundles and relocates Adventure) as the Spigot artifact instead.

Happy to submit a PR for Option A if that direction sounds right — I'm currently working on Paper 26.2 support in the same area.

### PR DESCRIPTION
**Pull request by HyacinthHaru**
**Fixes Spigot startup (broken since #998)** 

the Paper jar excludes adventure-api and MiniMessage (Paper provides them natively), but nothing supplied them on pure Spigot,so the plugin failed to load with `NoClassDefFoundError`. They are now resolved at runtime through the Spigot library loader (`plugin.yml` → `libraries:`), pinned via `adventure_version` / `adventure_platform_version``gradle.properties` alongside the other runtime libraries. Paper/Folia are unaffected, as `paper-plugin.yml` takes precedence there. Fixes #1005.

**Supports Minecraft 26.2 on Paper & Spigot:**

- `BukkitHuskHomes#getMinecraftVersion` now parses only the numeric prefix of the Bukkit version string. Paper reports versions like `26.2.build.62-beta` since 26.1, which made DesertWell's `Version#parse` throw `NumberFormatException: For input string: "build"` (breaking `/huskhomes status`).
- Bumped run-paper 2.3.1 → 3.0.2 (older versions use the retired download API and cannot fetch 26.2 builds); `runServer` now targets 26.2.
- Added 26.1.1 / 26.1.2 / 26.2 to the release workflow's published game versions.

**Testing**

- Audited all Adventure call sites in `common`/`bukkit` against the Adventure 4.x → 5 migration guide: no removed APIs in use.
- `:common:test` and `:bukkit:test` pass.

**Notes**

- Folia is not validated — there are no upstream Folia builds for 26.2 yet.
- Fabric is intentionally untouched; Fabric 26.2 support is #999 (no conflicting files).

### CODE REVIEW

**Comment by QarthO** [comment]
the adventure/minimessage port is still in alpha, and im still working on it internally. I'm only focused on paper support internally. Spigot is definitely on the backburner, and we might even drop support for it in the future especially as paper diverges more.

Closing for now. For future PRs make sure to break simpler/different goals into diff ones. ie. "Fix adventure errors in spigot", "fix version paper version parsing", "paper 26.2 support" etc.

**Comment by momo-OwO-qwq** [comment]
文字显示有小问题唔image

**Comment by QarthO** [comment]
> 文字显示有小问题唔image
> 
> 

Delete your messages file so it makes a new one. We switched to using MiniMessage instead of MineDown on the alpha builds.

We will have a better system in place letting you know once we publish a release.

Next time make an issue.

**Comment by momo-OwO-qwq** [comment]
> > 文字显示有小问题唔image
> 
> Delete your messages file so it makes a new one. We switched to using MiniMessage instead of MineDown on the alpha builds.请删除您的消息文件，这样系统会生成一个新的消息文件。在测试版本中，我们已改用 MiniMessage 来替代 MineDown。
> 
> We will have a better system in place letting you know once we publish a release.我们会建立更完善的机制，以便在发布新版本时及时通知您。
> 
> Next time make an issue.下次再提出来吧。

thank you~
